[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "C4", "SIM"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.per-file-ignores]
"__init__.py" = ["F401"]
